spring:
  application:
    name: user_subscription_service
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/subscription_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true